version: '3.9'

services:
  app:
    container_name: dsclients
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
    - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: dsclients
    volumes:
      - pgData:/var/lib/postgresql/data

volumes:
   pgData: